name: Mirror repo to GitLab

on: [push, pull_request, delete]

jobs:
  call-oceanai-mirror-workflow:
    uses: itmo-sai-code/OCEANAI/.github/workflows/mirror-repo.yml@master
    with:
      GITLAB_URL: 'https://gitlab.actcognitive.org/itmo-sai-code/oceanai.git'
    secrets:
      GITLAB_USER: ${{ secrets.GITLAB_USER }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
