name: Mirror repo to GitLab

on:
  workflow_call:
    inputs:
      GITLAB_URL:
        required: true
        type: string
    secrets:
      GITLAB_USER:
        required: true
      GITLAB_PASSWORD:
        required: true

jobs:
  call-oceanai-mirror-workflow:
    uses: DmitryRyumin/OCEANAI/.github/workflows/mirror-repo.yml@main
    with:
      GITLAB_URL: 'https://gitlab.actcognitive.org/itmo-sai-code/oceanai.git'
    secrets:
      GITLAB_USER: ${{ secrets.GITLAB_USER }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
