name: Mirror repo to GitLab

on:
  workflow_call:
    secrets:
      GITLAB_USER:
        required: true
      GITLAB_PASSWORD:
        required: true

jobs:
  call-nss-ops-mirror-workflow:
    uses: DmitryRyumin/OCEANAI/.github/workflows/mirror-repo.yml@main
    with:
      GITLAB_URL: 'https://gitlab.actcognitive.org/itmo-sai-code/oceanai'
    secrets:
      GITLAB_USER: ${{ secrets.GITLAB_USER }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
